pipeline {
    agent {
        node {
            label 'foo'
            customWorkspace '/tmp'
        }
    }

    stages {
        stage('Build') {
            steps { sh 'make' }
        }
    }
}
